### ISSUE TITLE
Laravel 10 cron

### ISSUE THREAD

**Issue by danharper83** [platformsh-templates/laravel#55]
### What in this template can be improved or added as a feature?

Laravel 10 scheduling requires cron to run every minute, this is currently not possible with platform so a work around needs to be documented.

### What exactly should be updated?

Cron schedule

### How important is this feature to you?

Scheduling is not useable in laravel 10

**Comment by danharper83** [comment]
I think adding this to the platfrom yaml should work

```
workers:
   queue:
       size: S
       commands:
           # To minimize leakage, the queue worker will stop every hour
           # and get restarted automatically.
           start: |
               php artisan schedule:work
```
